[project]
name = "spotifyrecommendation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask==3.0.2",
    "python-dotenv==1.1.0",
    "requests==2.32.3",
    "spotipy==2.25.1",
]
